<Project><PropertyGroup><Nullable>enable</Nullable><RuntimeIdentifiers>win-x64</RuntimeIdentifiers><ImplicitUsings>enable</ImplicitUsings><TreatWarningsAsErrors>true</TreatWarningsAsErrors><Deterministic>true</Deterministic><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile><Version>0.1.0</Version><Authors>krebs3r</Authors><RepositoryUrl>https://github.com/krebs3r/hourstone-companion</RepositoryUrl><PackageLicenseExpression>MIT</PackageLicenseExpression></PropertyGroup></Project>