using System.Globalization;
using System.Text;

namespace Hourstone.Companion.Core;

public static class DataAddonWriter
{
    public const string OwnershipMarker = "Hourstone Companion managed data addon v1";
    public static string BuildData(IEnumerable<string> selectedSourceIds, IEnumerable<Observation> union)
    {
        var observations = ObservationRules.Merge(union); var output = new StringBuilder("-- Generated by Hourstone Companion. Changes will be replaced.\nHourstoneSync = { formatVersion = 2, sources = {\n");
        foreach (var source in selectedSourceIds.Distinct(StringComparer.Ordinal).Order(StringComparer.Ordinal))
        {
            if (!ObservationRules.ValidSourceId(source)) throw new InvalidDataException("Invalid data addon source ID.");
            output.Append('[').Append(Quote(source)).Append("] = { observations = {\n");
            foreach (var observation in observations)
            {
                output.Append("{ sourceId=").Append(Quote(observation.SourceId)).Append(", region=").Append(Quote(observation.Region))
                    .Append(", flavor=").Append(Quote(observation.Flavor)).Append(", guid=").Append(Quote(observation.Guid))
                    .Append(", name=").Append(Quote(observation.Name)).Append(", realm=").Append(Quote(observation.Realm))
                    .Append(", class=").Append(Quote(observation.Class)).Append(", level=").Append(observation.Level)
                    .Append(", seconds=").Append(Number(observation.Seconds)).Append(", updatedAt=").Append(Number(observation.UpdatedAt));
                if (observation.Confirmed) output.Append(", serverSeconds=").Append(Number(observation.ServerSeconds!.Value)).Append(", serverAt=").Append(Number(observation.ServerAt!.Value));
                if (observation.Guild is not null) output.Append(", guild=").Append(Quote(observation.Guild)).Append(", guildUpdatedAt=").Append(Number(observation.GuildUpdatedAt!.Value));
                output.Append(" },\n");
            }
            output.Append("} },\n");
        }
        return output.Append("} }\n").ToString();
    }
    public static void Write(string clientDirectory, IEnumerable<string> selectedSourceIds, IEnumerable<Observation> union)
    {
        var directory = Path.Combine(Path.GetFullPath(clientDirectory), "Interface", "AddOns", "Hourstone_Sync");
        SafeFiles.EnsureNoReparsePoints(directory);
        var marker = Path.Combine(directory, ".hourstone-managed");
        if (Directory.Exists(directory) && Directory.EnumerateFileSystemEntries(directory).Any() && (!File.Exists(marker) || SafeFiles.StableRead(marker, 4096) != OwnershipMarker))
            throw new IOException("Hourstone_Sync already exists and is not owned by this companion.");
        SafeFiles.AtomicWriteOwned(directory, ".hourstone-managed", OwnershipMarker);
        // Data is committed before the initial TOC so the addon is never initially discoverable without data.
        SafeFiles.AtomicWriteOwned(directory, "Data.lua", BuildData(selectedSourceIds, union));
        SafeFiles.AtomicWriteOwned(directory, "Hourstone_Sync.toc", "## Interface: 120100, 50504, 20506, 11509\n## Title: Hourstone Sync Data\n## Notes: Local data managed by Hourstone Companion.\n## Version: 2.0.0\n## LoadOnDemand: 0\n\nData.lua\n");
    }
    public static string Quote(string value)
    {
        var output = new StringBuilder("\"");
        foreach (var c in value) output.Append(c switch
        { '\\' => "\\\\", '"' => "\\\"", '\n' => "\\n", '\r' => "\\r", '\t' => "\\t", < ' ' => "\\" + ((int)c).ToString("D3", CultureInfo.InvariantCulture), _ => c.ToString() });
        return output.Append('"').ToString();
    }
    private static string Number(double value) => value.ToString("R", CultureInfo.InvariantCulture);
}
